version: 2

jobs:
  build:
    working_directory: /home/circleci/laratools-ci
    machine: true

    steps:

      - checkout

      - setup_remote_docker

      - run:
          name: Build Images
          command: make build-all

  test:
    working_directory: /home/circleci/laratools-ci
    machine: true

    steps:

      - run:
          name: Test Images
          command: make test-all

  push:
    working_directory: /home/circleci/laratools-ci
    machine: true

    steps:

      - run:
          name: Push Images
          command: make push-all

workflows:
  version: 2

  deploy:
    jobs:
      - build

      - test:
          requires:
            - build

      - push:
          requires:
            - test
          filters:
            branches:
              only:
                - master