version: 2

jobs:
  build-and-test:
    working_directory: /home/circleci/laratools-ci

    docker:
      - image: docker:stable

    steps:

      - checkout

      - setup_remote_docker:
          version: 17.11.0-ce

      - run:
          name: Install build tools
          command: apk add --no-cache make git curl

      - run:
          name: Install goss
          command: |
            curl -fsSL https://goss.rocks/install | GOSS_VER=v0.3.5 GOSS_DST=/usr/local/bin sh
            alias dgoss="sh /usr/local/bin/dgoss"

      - run:
          name: Build Images
          command: make build-all

      - run:
          name: Test Images
          command: make test-all

  push:
    working_directory: /home/circleci/laratools-ci
    machine: true

    steps:

      - run:
          name: Push Images
          command: make push-all

workflows:
  version: 2

  deploy:
    jobs:
      - build-and-test

      - push:
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - master